### ISSUE TITLE
trackers working very slow

### ISSUE THREAD

**Issue by NazarovAV** [wwdguu/pyCFTrackers#11]
Hi! i tried your trackers on video and they work very slow for me (~10 second on iteration). i'm tried to use moose and kcf trackers.
i'm use:
cupy-cuda100                  7.1.1
mxnet-cu100                   1.5.1.post0
Cuda compilation tools, release 10.0, V10.0.130
what could be the problem?

**Comment by fengyang95** [comment]
I just implemented the algorithms and  did not consider too much about efficiency. Sorry for that. I only tested on cuda9.0
