### ISSUE TITLE
cannot import name '_gradient' from 'lib.eco.features' 

### ISSUE THREAD

**Issue by SmallCookier** [wwdguu/pyCFTrackers#12]
i can't import the '_gradient' by following steps. how can i solve this?

**Comment by fengyang95** [comment]
It seems that you didn't build ECO module properly. Maybe you should try to follow the install instructions in README.

**Comment by SmallCookier** [comment]
I  followed the install instructions. but it didn't work. what happen when I build eco module?

**Comment by fengyang95** [comment]
You may go to this repo https://github.com/StrangerZhang/pyECO for more details about installation of ECO.

**Comment by SmallCookier** [comment]
`running build_ext
building '_gradient' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: gcc -pthread -B /home/edison/anaconda3/envs/pytracking/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build/temp.linux-x86_64-3.7
compile options: '-I/home/edison/anaconda3/envs/pytracking/lib/python3.7/site-packages/numpy/core/include -I/home/edison/anaconda3/envs/pytracking/include/python3.7m -c'
gcc: gradient.cpp
gcc: _gradient.cpp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/edison/anaconda3/envs/pytracking/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:0,
                 from /home/edison/anaconda3/envs/pytracking/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/edison/anaconda3/envs/pytracking/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from _gradient.cpp:2:
/home/edison/anaconda3/envs/pytracking/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
gradient.cpp: In function ‘void gradMag(float*, float*, float*, int, int, int, bool)’:
gradient.cpp:76:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
         if( c==0 ) continue; _m = CMPGT( _M2[y1], _M2[y] );
         ^~
gradient.cpp:76:30: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
         if( c==0 ) continue; _m = CMPGT( _M2[y1], _M2[y] );
                              ^~
gradient.cpp: In function ‘void gradMagNorm(float*, float*, int, int, float)’:
gradient.cpp:109:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if(sse) i*=4; for(; i<n; i++) M[i] /= (S[i] + norm);
   ^~
gradient.cpp:109:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
   if(sse) i*=4; for(; i<n; i++) M[i] /= (S[i] + norm);
                 ^~~
g++ -pthread -shared -B /home/edison/anaconda3/envs/pytracking/compiler_compat -L/home/edison/anaconda3/envs/pytracking/lib -Wl,-rpath=/home/edison/anaconda3/envs/pytracking/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/_gradient.o build/temp.linux-x86_64-3.7/gradient.o -o /home/edison/projects/pyCFTrackers/lib/eco/features/_gradient.cpython-37m-x86_64-linux-gnu.so``
