### ISSUE TITLE
Evaluation results

### ISSUE THREAD

**Issue by TSSSS4** [wwdguu/pyCFTrackers#2]
It seems that your OTB100 result of ECO is lower than it paper and code from https://github.com/StrangerZhang/pyECO, do you have any idea about how to fix this?

 I got a success of 0.683 and precision of 0.911 using code from pyECO.

**Comment by fengyang95** [comment]
I am trying to  fix it. Do you use the  pysot-toolkit to eval?  I  have changed some config params.

**Comment by fengyang95** [comment]
could you please share your eval code with me? My eval results on VOT are also lower than that in the code.

**Comment by TSSSS4** [comment]
qq: 970671081

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Yuanpeng Li <notifications@github.com>
发送时间: Monday, April 8, 2019 1:19:38 PM
收件人: wwdguu/pyCFTrackers
抄送: TSSSS4; Author
主题: Re: [wwdguu/pyCFTrackers] Evaluation results (#2)


could you please share your eval code with me? My eval results on VOT are also lower than that in the code.

―

**Comment by fengyang95** [comment]
加不了 我的是2549480345
