### ISSUE TITLE
The speed of BACF

### ISSUE THREAD

**Issue by Xianqi-Zhang** [wwdguu/pyCFTrackers#3]
Hello,
Thank you for sharing.
I try BACF on my server and only ~10fps (OTB100), w/o loading images. Could u tell me the speed of the BACF when u test ?

Thanks for your help!

**Comment by fengyang95** [comment]
I also get the similar speed of ~10 fps, you can check my log files 'log_test_vot2016.txt' and 'log_test_vot2018.txt' in eval dir.

**Comment by Xianqi-Zhang** [comment]
Thank for your reply.
The speed in his paper and web is ~35fps.
The main reason is matlab and python or some other things?
Do u have any advices?

**Comment by fengyang95** [comment]
Sorry, I'm also not very sure yet. Maybe using some tricks such as numba can achieve a faster speed.

**Comment by Xianqi-Zhang** [comment]
Thank you ! ! !
