### ISSUE TITLE
GOT-10k eval result

### ISSUE THREAD

**Issue by Xianqi-Zhang** [wwdguu/pyCFTrackers#5]
Hello,
I have test the BACF with the  toolkit GOT-10k (https://github.com/got-10k/toolkit) on OTB100, but the score is much lower than the pysot. (I can't run the pysot on my server and have no idea.)
----------------------------------------------------------
GOT10k:  | precision 0.622   |  sucess 0.462
pysot:      | precision 0.796   |  sucess 0.598
----------------------------------------------------------
Do you have any idea about this?
Is there any other toolkit can evaluate the python tracker? 

Thank you for any reply.

**Comment by fengyang95** [comment]
Did you test other trackers such as KCF? They all get lower score  when using got-10k  toolkit to eval?

**Comment by Xianqi-Zhang** [comment]
Hi，
I have tried CSK and DCF-HOG, this 2 trackers achieve higher score with GOT10k
---------------------------------------------------------------
GOT10K  CSK   0.520  0.387   
pysot      CSK   0.494 0.375
GOT10K  DCF   0.700  0.485   
pysot      DCF   0.695  0.482

**Comment by fengyang95** [comment]
could you share the evalution code with me? cause i don't know how you eval it.
