### ISSUE TITLE
Setting up the data sets. 

### ISSUE THREAD

**Issue by prerit1998jain** [wwdguu/pyCFTrackers#9]
Can you share the file structure of your codebase, i.e locations of datasets wrt cf_demo.py.

**Comment by fengyang95** [comment]
├── LICENSE
├── README.md    
├── dataset
│   ├── OTB
│   ├── VOT2016
│   ├── VOT2018
│   └── test

**Comment by prerit1998jain** [comment]
What have you kept in the test folder? The json files ?
